### ISSUE TITLE
Automation Checklist

### ISSUE THREAD

**Issue by jeandersonbc** [jeandersonbc/home-sweet-home#1]
Things that I would like to learn and get it done in this project:

- [x] Vagrant integration and tooling provisioning so I can deploy my development environment in any situation and scenario. 
- [ ] Continuous Integration to build my webpage
- [ ] Automatically deployment and publish to jeandersonbc.github.io
